# Generated by Django 4.2.4 on 2023-08-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStoreModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('taksTitle', models.CharField(max_length=20)),
                ('taskDescription', models.CharField(max_length=150)),
                ('isCompleted', models.BooleanField(default=False)),
            ],
        ),
    ]
