# Generated by Django 4.2.4 on 2023-08-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskstoremodel',
            old_name='taksTitle',
            new_name='taskTitle',
        ),
    ]
